Reformat shell scripts

diff --git a/bin/antivirus b/bin/antivirus
--- a/bin/antivirus
+++ b/bin/antivirus
@@ -4,26 +4,26 @@ set -e -u -o pipefail
 # set -x
 
 info() {
-    echo -e "\\x1b[32m\\xE2\\x87\\x92 $1\\x1b[0m"
+  echo -e "\\x1b[32m\\xE2\\x87\\x92 $1\\x1b[0m"
 }
 
 error() {
-    echo -e "\\x1b[97m\\x1b[41m\\x21\\x1b[0m \\x1b[31m$1\\x1b[0m" 1>&2
-    exit 1
+  echo -e "\\x1b[97m\\x1b[41m\\x21\\x1b[0m \\x1b[31m$1\\x1b[0m" 1>&2
+  exit 1
 }
 
 main() {
-    local command=${1:-}
+  local command=${1:-}
 
-    if [[ $command = full ]]; then
-        info "Running full scan..."
-        clamscan --recursive --infected --bell --exclude-dir='^/sys|^/dev' --remove /
-    elif [[ $command = quick ]]; then
-        info "Running quick scan..."
-        sudo clamscan --recursive --infected --bell --remove /home
-    else
-        error "Invalid command '${command}'! Command must equal to 'full' or quick!"
-    fi
+  if [[ $command = full ]]; then
+    info "Running full scan..."
+    clamscan --recursive --infected --bell --exclude-dir='^/sys|^/dev' --remove /
+  elif [[ $command = quick ]]; then
+    info "Running quick scan..."
+    sudo clamscan --recursive --infected --bell --remove /home
+  else
+    error "Invalid command '${command}'! Command must equal to 'full' or quick!"
+  fi
 }
 
 main "$@"
diff --git a/bin/arch-update b/bin/arch-update
--- a/bin/arch-update
+++ b/bin/arch-update
@@ -6,38 +6,38 @@ set -e -u -o pipefail
 declare -r script=$(basename "$0")
 
 info() {
-    echo -e "\\x1b[1;38;5;57m::\\x1b[39m $1\\x1b[0m"
+  echo -e "\\x1b[1;38;5;57m::\\x1b[39m $1\\x1b[0m"
 }
 
 msg() {
-    echo -e "\\x1b[1;33m==>\\x1b[39m $1\\x1b[0m"
+  echo -e "\\x1b[1;33m==>\\x1b[39m $1\\x1b[0m"
 }
 
 sub_msg() {
-    echo -e "  \\x1b[1;38;5;57m->\\x1b[39m $1\\x1b[0m"
+  echo -e "  \\x1b[1;38;5;57m->\\x1b[39m $1\\x1b[0m"
 }
 
 error() {
-    echo -e "\\x1b[1;97m\\x1b[41m\\x21\\x1b[0m \\x1b[31m$1\\x1b[0m" 1>&2
-    exit 1
+  echo -e "\\x1b[1;97m\\x1b[41m\\x21\\x1b[0m \\x1b[31m$1\\x1b[0m" 1>&2
+  exit 1
 }
 
 warning() {
-    echo -e "\\x1b[1;95m===>\\x1b[39m $1\\x1b[0m" 1>&2
+  echo -e "\\x1b[1;95m===>\\x1b[39m $1\\x1b[0m" 1>&2
 }
 
 play_sound() {
-    local noise=/usr/share/sounds/freedesktop/stereo/complete.oga
+  local noise=/usr/share/sounds/freedesktop/stereo/complete.oga
 
-    if [[ -f "${noise}" ]]; then
-        vlc --play-and-exit "${noise}"
-    else
-        warning "Sound notification file '${noise}' does not exist."
-    fi
+  if [[ -f "${noise}" ]]; then
+    vlc --play-and-exit "${noise}"
+  else
+    warning "Sound notification file '${noise}' does not exist."
+  fi
 }
 
 read_help() {
-    cat <<eom
+  cat <<eom
 ${script}
 
 A simple utility to upgrade Archlinux & AUR packages.
@@ -52,141 +52,141 @@ eom
 }
 
 show_usage() {
-    echo -e "$(read_help)" 1>&2
-    exit 1
+  echo -e "$(read_help)" 1>&2
+  exit 1
 }
 
 update_aur_package() {
-    local path="${1}"
-    local dirname=$(basename "$path")
+  local path="${1}"
+  local dirname=$(basename "$path")
 
-    msg "Updating \\x1b[33m${dirname}\\x1b[39m..."
+  msg "Updating \\x1b[33m${dirname}\\x1b[39m..."
 
-    cd "$path" || error "Could not enter directory '$path'"
+  cd "$path" || error "Could not enter directory '$path'"
 
-    if [[ -d .git ]]; then
-        git remote update
+  if [[ -d .git ]]; then
+    git remote update
 
-        local local_id=$(git rev-parse master)
-        local remote_id=$(git rev-parse origin/master)
+    local local_id=$(git rev-parse master)
+    local remote_id=$(git rev-parse origin/master)
 
-        if [[ "$local_id" != "$remote_id" ]]; then
-            sub_msg "Pulling latest changes..."
-            git pull
+    if [[ "$local_id" != "$remote_id" ]]; then
+      sub_msg "Pulling latest changes..."
+      git pull
 
-            # @TODO add a step to verify the files
-            sub_msg "Building package..."
-            makepkg --syncdeps --install --rmdeps --clean
-        else
-            sub_msg "\\x1b[33m${dirname}\\x1b[39m is up-to-date"
-        fi
+      # @TODO add a step to verify the files
+      sub_msg "Building package..."
+      makepkg --syncdeps --install --rmdeps --clean
     else
-        warning "\\x1b[33m${dirname}\\x1b[39m is not a git repository. Skipping."
+      sub_msg "\\x1b[33m${dirname}\\x1b[39m is up-to-date"
     fi
+  else
+    warning "\\x1b[33m${dirname}\\x1b[39m is not a git repository. Skipping."
+  fi
 }
 
 update_aur_packages() {
-    info "Updating AUR packages..."
+  info "Updating AUR packages..."
 
-    [[ ! -d "${AUR_PKG}" ]] && error "AUR directory '${AUR_PKG}' does not exist"
+  [[ ! -d "${AUR_PKG}" ]] && error "AUR directory '${AUR_PKG}' does not exist"
 
-    msg "Scanning directory \\x1b[33m${AUR_PKG}\\x1b[39m"
+  msg "Scanning directory \\x1b[33m${AUR_PKG}\\x1b[39m"
 
-    local repositories=$(find "$AUR_PKG" -maxdepth 1 -type d ! -path "$AUR_PKG")
+  local repositories=$(find "$AUR_PKG" -maxdepth 1 -type d ! -path "$AUR_PKG")
 
-    for repository in ${repositories[*]}; do
-        update_aur_package "$repository"
-    done
+  for repository in ${repositories[*]}; do
+    update_aur_package "$repository"
+  done
 }
 
 update_arch_packages() {
-    info "Updating Arch packages..."
+  info "Updating Arch packages..."
 
-    printf "Shall we check the Archlinux news? [Y/n]: "
-    read -r check_news
+  printf "Shall we check the Archlinux news? [Y/n]: "
+  read -r check_news
 
-    [[ -z "$check_news" ]] && check_news=y
+  [[ -z "$check_news" ]] && check_news=y
 
-    if [[ "$check_news" = y ]]; then
-        xdg-open https://www.archlinux.org
-    fi
+  if [[ "$check_news" = y ]]; then
+    xdg-open https://www.archlinux.org
+  fi
 
-    sudo pacman -Syu
+  sudo pacman -Syu
 
-    printf "Do you need to run pacdiff? [y/N]: "
-    read -r run_pacdiff
+  printf "Do you need to run pacdiff? [y/N]: "
+  read -r run_pacdiff
 
-    if [[ "$run_pacdiff" = y ]]; then
-        sudo pacdiff
-    fi
+  if [[ "$run_pacdiff" = y ]]; then
+    sudo pacdiff
+  fi
 }
 
 check_orphans() {
-    info "Looking up orphans..."
+  info "Looking up orphans..."
 
-    local orphans=()
+  local orphans=()
 
-    IFS=" " read -r -a orphans <<<"$(sudo pacman -Qtdq)"
+  IFS=" " read -r -a orphans <<<"$(sudo pacman -Qtdq)"
 
-    if [[ ${#orphans[@]} -eq 0 ]]; then
-        msg "No orphans found"
-    else
-        printf "The following orphaned packages have been found: "
-        echo -e "${orphans[@]}"
+  if [[ ${#orphans[@]} -eq 0 ]]; then
+    msg "No orphans found"
+  else
+    printf "The following orphaned packages have been found: "
+    echo -e "${orphans[@]}"
 
-        printf "Do you want to remove them? [y/N]: "
-        read -r remove_pkgs
+    printf "Do you want to remove them? [y/N]: "
+    read -r remove_pkgs
 
-        if [[ "$remove_pkgs" = y ]]; then
-            sudo pacman -Rns "${orphans[@]}"
-        fi
+    if [[ "$remove_pkgs" = y ]]; then
+      sudo pacman -Rns "${orphans[@]}"
     fi
+  fi
 }
 
 clean_cache() {
-    local keep=2
+  local keep=2
 
-    info "Looking up unnecessary packages in cache..."
-    sudo paccache -dk "$keep"
+  info "Looking up unnecessary packages in cache..."
+  sudo paccache -dk "$keep"
 
-    printf "Do you want to clean up the cache (keeping %s last version(s))? [y/N]: " $keep
-    read -r clean_cache
+  printf "Do you want to clean up the cache (keeping %s last version(s))? [y/N]: " $keep
+  read -r clean_cache
 
-    if [[ "$clean_cache" = y ]]; then
-        sudo paccache -rk "$keep"
-    fi
+  if [[ "$clean_cache" = y ]]; then
+    sudo paccache -rk "$keep"
+  fi
 }
 
 main() {
-    if [[ $EUID -eq 0 ]]; then
-        error "This script must NOT be run as root"
+  if [[ $EUID -eq 0 ]]; then
+    error "This script must NOT be run as root"
+  fi
+
+  local -r option="${1:-}"
+
+  if [[ "$option" != --help ]]; then
+    if [[ "$option" != --aur-only ]]; then
+      update_arch_packages
     fi
 
-    local -r option="${1:-}"
-
-    if [[ "$option" != --help ]]; then
-        if [[ "$option" != --aur-only ]]; then
-            update_arch_packages
-        fi
-
-        if [[ "$option" != --arch-only ]]; then
-            update_aur_packages
-            check_orphans
-        fi
-
-        clean_cache
-
-        printf "Shall we reboot Archlinux? [y/N]: "
-        read -r should_reboot
-
-        [[ -z "$should_reboot" ]] && should_reboot=n
-
-        if [[ "$should_reboot" = y ]]; then
-            reboot
-        fi
-    else
-        show_usage
+    if [[ "$option" != --arch-only ]]; then
+      update_aur_packages
+      check_orphans
     fi
+
+    clean_cache
+
+    printf "Shall we reboot Archlinux? [y/N]: "
+    read -r should_reboot
+
+    [[ -z "$should_reboot" ]] && should_reboot=n
+
+    if [[ "$should_reboot" = y ]]; then
+      reboot
+    fi
+  else
+    show_usage
+  fi
 }
 
 main "$@"
diff --git a/bin/aur-install b/bin/aur-install
--- a/bin/aur-install
+++ b/bin/aur-install
@@ -6,16 +6,16 @@ set -e -u -o pipefail
 declare -r script=$(basename "$0")
 
 msg() {
-    echo -e "\\x1b[1;33m==>\\x1b[39m $1\\x1b[0m"
+  echo -e "\\x1b[1;33m==>\\x1b[39m $1\\x1b[0m"
 }
 
 error() {
-    echo -e "\\x1b[1;97m\\x1b[41m\\x21\\x1b[0m \\x1b[31m$1\\x1b[0m" 1>&2
-    exit 1
+  echo -e "\\x1b[1;97m\\x1b[41m\\x21\\x1b[0m \\x1b[31m$1\\x1b[0m" 1>&2
+  exit 1
 }
 
 read_help() {
-    cat <<eom
+  cat <<eom
 ${script}
 
 A simple utility to install AUR packages.
@@ -31,10 +31,10 @@ eom
 }
 
 get_confirmation_message() {
-    local name=$1
-    local url=$2
+  local name=$1
+  local url=$2
 
-    cat <<EOM
+  cat <<EOM
 You are about to install the following package:
 - Name: \\x1b[33m${name}\\x1b[0m
 - URL: \\x1b[33m${url}\\x1b[0m
@@ -43,44 +43,44 @@ EOM
 }
 
 show_usage() {
-    echo -e "$(read_help)" 1>&2
-    exit 1
+  echo -e "$(read_help)" 1>&2
+  exit 1
 }
 
 install_aur_package() {
-    local url="${1}"
-    local name=$(basename "$url" .git)
-    local message=$(get_confirmation_message "$name" "$url")
+  local url="${1}"
+  local name=$(basename "$url" .git)
+  local message=$(get_confirmation_message "$name" "$url")
 
-    cd "$AUR_PKG" || error "Cannot enter directory '$AUR_PKG'"
+  cd "$AUR_PKG" || error "Cannot enter directory '$AUR_PKG'"
 
-    msg "Working directory \\x1b[33m$(pwd)\\x1b[39m"
+  msg "Working directory \\x1b[33m$(pwd)\\x1b[39m"
 
-    read -erp "$(echo -e "$message")" answer
+  read -erp "$(echo -e "$message")" answer
 
-    if [[ "$answer" = y ]]; then
-        git clone "${url}"
+  if [[ "$answer" = y ]]; then
+    git clone "${url}"
 
-        cd "./${name}" || error "Cannot enter directory '${name}'"
+    cd "./${name}" || error "Cannot enter directory '${name}'"
 
-        makepkg --syncdeps --install --rmdeps --clean
-    else
-        msg "The package \\x1b[33m${name}\\x1b[39m was not installed"
-    fi
+    makepkg --syncdeps --install --rmdeps --clean
+  else
+    msg "The package \\x1b[33m${name}\\x1b[39m was not installed"
+  fi
 }
 
 main() {
-    if [[ $EUID -eq 0 ]]; then
-        error "This script must NOT be run as root"
-    fi
+  if [[ $EUID -eq 0 ]]; then
+    error "This script must NOT be run as root"
+  fi
 
-    local -r url="${1:-}"
+  local -r url="${1:-}"
 
-    if [[ "$url" == http* ]]; then
-        install_aur_package "${url}"
-    else
-        show_usage
-    fi
+  if [[ "$url" == http* ]]; then
+    install_aur_package "${url}"
+  else
+    show_usage
+  fi
 }
 
 main "$@"
diff --git a/bin/gen-certificate b/bin/gen-certificate
--- a/bin/gen-certificate
+++ b/bin/gen-certificate
@@ -11,116 +11,116 @@ declare -r ssl_certs_organization="Mickael Vieira"
 declare -r default_cert_name="cert-$(date +%Y-%m-%d)"
 
 info() {
-    printf "\\x1b[32m\\xE2\\x87\\x92 %s\\x1b[0m\\n" "$1"
+  printf "\\x1b[32m\\xE2\\x87\\x92 %s\\x1b[0m\\n" "$1"
 }
 
 error() {
-    printf "\\x1b[97m\\x1b[41m\\x21\\x1b[0m \\x1b[31m%s\\x1b[0m\\n" "$1" 1>&2
-    exit 1
+  printf "\\x1b[97m\\x1b[41m\\x21\\x1b[0m \\x1b[31m%s\\x1b[0m\\n" "$1" 1>&2
+  exit 1
 }
 
 warning() {
-    printf "\\x1b[97m\\x1b[45m\\x21\\x1b[0m \\x1b[35m%s\\x1b[0m\\n" "$1"
+  printf "\\x1b[97m\\x1b[45m\\x21\\x1b[0m \\x1b[35m%s\\x1b[0m\\n" "$1"
 }
 
 prompt() {
-    printf "\\x1b[93m%s: \\x1b[0m" "$1"
+  printf "\\x1b[93m%s: \\x1b[0m" "$1"
 }
 
 is_install() {
-    command -v "$1" > /dev/null 2>&1 || error "'$1' (command not found)"
+  command -v "$1" >/dev/null 2>&1 || error "'$1' (command not found)"
 }
 
 create_destination() {
-    local path="$1";
-    mkdir -vp "$path" || return
+  local path="$1"
+  mkdir -vp "$path" || return
 }
 
 gen_fields() {
-    printf "/C=%s/ST=%s/L=%s/O=%s/CN=%s" \
-        "$ssl_certs_country" \
-        "$ssl_certs_state" \
-        "$ssl_certs_locality" \
-        "$ssl_certs_organization" \
-        "$1"
+  printf "/C=%s/ST=%s/L=%s/O=%s/CN=%s" \
+    "$ssl_certs_country" \
+    "$ssl_certs_state" \
+    "$ssl_certs_locality" \
+    "$ssl_certs_organization" \
+    "$1"
 }
 
 generate_rsa_key() {
-    local key_path="$1";
-    openssl genrsa -out "${key_path}" 2048
+  local key_path="$1"
+  openssl genrsa -out "${key_path}" 2048
 }
 
 generate_csr() {
-    local cert_name="$1"
-    local key_path="$2"
-    local csr_path="$3"
+  local cert_name="$1"
+  local key_path="$2"
+  local csr_path="$3"
 
-    [[ -f "$key_path" ]] || error "Private Key not found"
+  [[ -f "$key_path" ]] || error "Private Key not found"
 
-    openssl req -new -sha256 \
-        -subj "$(gen_fields "$cert_name")" \
-        -key "$key_path" \
-        -out "$csr_path"
+  openssl req -new -sha256 \
+    -subj "$(gen_fields "$cert_name")" \
+    -key "$key_path" \
+    -out "$csr_path"
 }
 
 generate_ssl_certificate() {
-    local key_path="$1"
-    local csr_path="$2"
-    local cert_path="$3"
+  local key_path="$1"
+  local csr_path="$2"
+  local cert_path="$3"
 
-    [[ -f "$key_path" ]] || error "Private Key not found"
-    [[ -f "$csr_path" ]] || error "Certificate Signing Request not found"
+  [[ -f "$key_path" ]] || error "Private Key not found"
+  [[ -f "$csr_path" ]] || error "Certificate Signing Request not found"
 
-    openssl req -nodes -x509 \
-        -days 365 \
-        -in "$csr_path" \
-        -key "$key_path" \
-        -out "$cert_path" \
-        -extensions v3_ca
+  openssl req -nodes -x509 \
+    -days 365 \
+    -in "$csr_path" \
+    -key "$key_path" \
+    -out "$cert_path" \
+    -extensions v3_ca
 }
 
 main() {
-    is_install openssl
+  is_install openssl
 
-    read -erp "$(prompt "Enter the certificate's name? ($default_cert_name)")" cert_name
+  read -erp "$(prompt "Enter the certificate's name? ($default_cert_name)")" cert_name
 
-    [[ -z "$cert_name" ]] && cert_name=$default_cert_name
+  [[ -z "$cert_name" ]] && cert_name=$default_cert_name
 
-    local path="/tmp/$cert_name"
-    local archive="$cert_name.tgz"
+  local path="/tmp/$cert_name"
+  local archive="$cert_name.tgz"
 
-    create_destination "$path"
+  create_destination "$path"
 
-    local key_path="$path/privkey.pem"
-    local csr_path="$path/csr.pem"
-    local cert_path="$path/fullchain.pem"
+  local key_path="$path/privkey.pem"
+  local csr_path="$path/csr.pem"
+  local cert_path="$path/fullchain.pem"
 
-    info "Generating private key"
-    generate_rsa_key "$key_path"
+  info "Generating private key"
+  generate_rsa_key "$key_path"
 
-    info "Generating Certificate Signing Request"
-    generate_csr "$cert_name" "$key_path" "$csr_path"
+  info "Generating Certificate Signing Request"
+  generate_csr "$cert_name" "$key_path" "$csr_path"
 
-    info "Generating SSL certificate"
-    generate_ssl_certificate "$key_path" "$csr_path" "$cert_path"
+  info "Generating SSL certificate"
+  generate_ssl_certificate "$key_path" "$csr_path" "$cert_path"
 
-    printf "\\x1b[32mThe certificate was generated in \\x1b[93m%s\\x1b[0m\\n" "$path"
-    printf "\\x1b[93m%s\\x1b[0m\\n" "$(ls -1 "$path")"
+  printf "\\x1b[32mThe certificate was generated in \\x1b[93m%s\\x1b[0m\\n" "$path"
+  printf "\\x1b[93m%s\\x1b[0m\\n" "$(ls -1 "$path")"
 
-    read -erp "$(prompt "Do you want to create an archive? (Y/n)")" do_archive
+  read -erp "$(prompt "Do you want to create an archive? (Y/n)")" do_archive
 
-    [[ -z "$do_archive" ]] && do_archive="y"
+  [[ -z "$do_archive" ]] && do_archive="y"
 
-    if [[ "$do_archive" == "y" ]]; then
-        tar czvf "$archive" -C /tmp "$cert_name"
-        rm -rf "${path}"
-        printf "\\x1b[32mArchive is ready \\x1b[93m%s\\x1b[0m\\n" "$(pwd)/$archive"
-    else
-        mv "$path" .
-        printf "\\x1b[32mFiles are ready in \\x1b[93m%s\\x1b[0m\\n" "$(pwd)/$cert_name"
-    fi
+  if [[ "$do_archive" == "y" ]]; then
+    tar czvf "$archive" -C /tmp "$cert_name"
+    rm -rf "${path}"
+    printf "\\x1b[32mArchive is ready \\x1b[93m%s\\x1b[0m\\n" "$(pwd)/$archive"
+  else
+    mv "$path" .
+    printf "\\x1b[32mFiles are ready in \\x1b[93m%s\\x1b[0m\\n" "$(pwd)/$cert_name"
+  fi
 
-    exit 0
+  exit 0
 }
 
 main
diff --git a/bin/gen-ssh-key b/bin/gen-ssh-key
--- a/bin/gen-ssh-key
+++ b/bin/gen-ssh-key
@@ -6,62 +6,62 @@ set -u -e -o pipefail
 declare -r default_user_email="contact@mickael-vieira.com"
 
 info() {
-    printf "\\x1b[32m\\xE2\\x87\\x92 %s\\x1b[0m\\n" "$1"
+  printf "\\x1b[32m\\xE2\\x87\\x92 %s\\x1b[0m\\n" "$1"
 }
 
 error() {
-    printf "\\x1b[97m\\x1b[41m\\x21\\x1b[0m \\x1b[31m%s\\x1b[0m\\n" "$1" 1>&2
-    exit 1
+  printf "\\x1b[97m\\x1b[41m\\x21\\x1b[0m \\x1b[31m%s\\x1b[0m\\n" "$1" 1>&2
+  exit 1
 }
 
 warning() {
-    printf "\\x1b[97m\\x1b[45m\\x21\\x1b[0m \\x1b[35m%s\\x1b[0m\\n" "$1"
+  printf "\\x1b[97m\\x1b[45m\\x21\\x1b[0m \\x1b[35m%s\\x1b[0m\\n" "$1"
 }
 
 prompt() {
-    printf "\\x1b[93m%s: \\x1b[0m" "$1"
+  printf "\\x1b[93m%s: \\x1b[0m" "$1"
 }
 
 is_install() {
-    command -v "$1" > /dev/null 2>&1 || error "'$1' (command not found)"
+  command -v "$1" >/dev/null 2>&1 || error "'$1' (command not found)"
 }
 
 create_destination() {
-    local path="$1";
-    mkdir -vp "$path" || return
+  local path="$1"
+  mkdir -vp "$path" || return
 }
 
 main() {
-    is_install ssh-keygen
+  is_install ssh-keygen
 
-    read -erp "$(prompt "Enter the user's email ($default_user_email)")" user_email
+  read -erp "$(prompt "Enter the user's email ($default_user_email)")" user_email
 
-    [[ -z "$user_email" ]] && user_email=$default_user_email
+  [[ -z "$user_email" ]] && user_email=$default_user_email
 
-    read -erp "$(prompt "Enter the directory's name")" target_name
+  read -erp "$(prompt "Enter the directory's name")" target_name
 
-    [[ -z "$target_name" ]] && error "Target directory cannot be empty!"
+  [[ -z "$target_name" ]] && error "Target directory cannot be empty!"
 
-    local -r key_name="id_rsa"
-    local -r target_dir="$HOME/.ssh/$target_name"
+  local -r key_name="id_rsa"
+  local -r target_dir="$HOME/.ssh/$target_name"
 
-    printf "The following files are about to be generated:\\n"
-    printf "%s/%s\\n" "$target_dir" "$key_name"
-    printf "%s/%s.pub\\n" "$target_dir" "$key_name"
+  printf "The following files are about to be generated:\\n"
+  printf "%s/%s\\n" "$target_dir" "$key_name"
+  printf "%s/%s.pub\\n" "$target_dir" "$key_name"
 
-    read -erp "$(prompt "Do you want to proceed [Y/n]")" confirm
+  read -erp "$(prompt "Do you want to proceed [Y/n]")" confirm
 
-    if [[ ${confirm} = n ]]; then
-        info "Skipped!"
-    else
-        info "Creating target directory ${target_dir}..."
-        [[ ! -d "$target_dir" ]] && create_destination "$target_dir"
+  if [[ ${confirm} = n ]]; then
+    info "Skipped!"
+  else
+    info "Creating target directory ${target_dir}..."
+    [[ ! -d "$target_dir" ]] && create_destination "$target_dir"
 
-        info "Generating ssh key..."
-        ssh-keygen -t rsa -b 4096 -C "$user_email" -N "" -f "$target_dir/$key_name"
-    fi
+    info "Generating ssh key..."
+    ssh-keygen -t rsa -b 4096 -C "$user_email" -N "" -f "$target_dir/$key_name"
+  fi
 
-    exit 0
+  exit 0
 }
 
 main
