refactor: update dotfiles install script

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -1,6 +1,5 @@
 #!/bin/bash
-# shellcheck disable=SC2155
-# shellcheck disable=SC1090
+# shellcheck disable=SC2048
 
 set -e -u -o pipefail
 # set -x
@@ -10,96 +9,81 @@ declare -r HOME_DIR=${HOME:-}
 declare -r ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
 declare -r PLATFORM=$(uname)
 
-read_help() {
+source "$(dirname "${BASH_SOURCE[0]}")/../lib/logging.sh"
+
+dotfiles::install::read_help() {
   cat <<eom
 This script helps me move into a new environment.
 
-$(highlight Usage):
+$(dotfiles::log::highlight Usage):
   ${SCRIPT} [command]
 
-$(highlight Commands):
+$(dotfiles::log::highlight Commands):
 - install:    install configuration files
 - check:      list of available services
 - help:       show this help
 
-$(highlight Examples):
+$(dotfiles::log::highlight Examples):
   ${SCRIPT} install               (install configuration files)
   ${SCRIPT} check                 (check dependencies)
 eom
 }
 
-usage() {
-  echo -e "\\n$(read_help)\\n" 1>&2
+dotfiles::install::usage() {
+  echo -e "\\n$(dotfiles::install::read_help)\\n" 1>&2
   exit 0
 }
 
-highlight() {
-  echo -e "\\x1b[33m$1\\x1b[0m"
-}
-
-info() {
-  echo -e "\\x1b[1;33m==>\\x1b[39m $1\\x1b[0m"
-}
-
-fatal() {
-  echo -e "\\x1b[97m\\x1b[41m\\x21\\x1b[0m \\x1b[31m$1\\x1b[0m" 1>&2
-  exit 1
-}
-
-warn() {
-  echo -e "\\x1b[1;95m==>\\x1b[39m $1\\x1b[0m" 1>&2
-}
-
-is_installed() {
+dotfiles::install::is_command_installed() {
   command -v "$1" >/dev/null 2>&1
 }
 
-get_install_command() {
+dotfiles::install::get_install_command() {
   local cmd=""
 
-  if is_installed apt; then
+  if dotfiles::install::is_command_installed apt; then
     cmd="apt install"
-  elif is_installed pacman; then
+  elif dotfiles::install::is_command_installed pacman; then
     cmd="pacman -S"
-  elif is_installed apt-get; then
+  elif dotfiles::install::is_command_installed apt-get; then
     cmd="apt-get install"
-  elif is_installed brew; then
+  elif dotfiles::install::is_command_installed brew; then
     cmd="brew install"
   fi
 
   echo "$cmd"
 }
 
-create_symlink() {
+dotfiles::install::create_symlink() {
   local target="$1"
   local symlink="$2"
   local backup="${symlink}.orig"
 
   if [[ (-f $symlink && ! -L $symlink) || -d $symlink ]]; then
-    info "moving existing location $symlink to $backup"
+    dotfiles::log::info "moving existing location $symlink to $backup"
     mv "$symlink" "$backup"
   fi
 
   if [[ ! -f $target && ! -d $target ]]; then
-    fatal "target $target is neither a file nor a directory"
+    dotfiles::log::fatal "target $target is neither a file nor a directory"
   fi
 
-  info "creating symlink $symlink"
+  dotfiles::log::info "creating symlink $symlink"
   ln -svf "$target" "$symlink"
 }
 
-ask_confirm() {
+dotfiles::install::ask_confirm() {
   local answer=
   local name="$1"
 
-  read -epr "$(echo -e "Do you want to install $(highlight "$name") configuration? [Y/n]:") " answer
+  read -epr "$(echo -e "Do you want to install $(dotfiles::log::highlight "$name") configuration? [Y/n]:") " answer
 
   [[ -z $answer ]] && answer="y"
 
-  echo $answer
+  echo "$answer"
 }
 
-install_bash() {
+dotfiles::install::bash() {
   local files=(
     .bashrc
     .bash_prompt
@@ -114,13 +98,13 @@ install_bash() {
   )
 
   for file in ${files[*]}; do
-    create_symlink "$ROOT_DIR/bash/$file" "$HOME_DIR/$file"
+    dotfiles::install::create_symlink "$ROOT_DIR/bash/$file" "$HOME_DIR/$file"
   done
 
-  source ~/.bashrc
+  source "$HOME_DIR/.bashrc"
 }
 
-install_git() {
+dotfiles::install::git() {
   local files=(
     .gitconfig
     .gitignore
@@ -129,33 +113,33 @@ install_git() {
   )
 
   for file in ${files[*]}; do
-    create_symlink "$ROOT_DIR/git/$file" "$HOME_DIR/$file"
+    dotfiles::install::create_symlink "$ROOT_DIR/git/$file" "$HOME_DIR/$file"
   done
 }
 
-install_vim() {
-  create_symlink "$ROOT_DIR/vim/.vim" "$HOME_DIR/.vim"
-  create_symlink "$ROOT_DIR/vim/.vimrc" "$HOME_DIR/.vimrc"
+dotfiles::install::vim() {
+  dotfiles::install::create_symlink "$ROOT_DIR/vim/.vim" "$HOME_DIR/.vim"
+  dotfiles::install::create_symlink "$ROOT_DIR/vim/.vimrc" "$HOME_DIR/.vimrc"
 
-  info "Fetching plug.vim"
+  dotfiles::log::info "Fetching plug.vim"
   curl -s https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim \
     -o "$HOME_DIR/.vim/autoload/plug.vim"
 
-  warn "Don't forget to run PlugInstall!"
+  dotfiles::log::warn "Don't forget to run PlugInstall!"
 }
 
-install_tmux() {
-  create_symlink "$ROOT_DIR/tmux/.tmux.conf" "$HOME_DIR/.tmux.conf"
+dotfiles::install::tmux() {
+  dotfiles::install::create_symlink "$ROOT_DIR/tmux/.tmux.conf" "$HOME_DIR/.tmux.conf"
 }
 
-install_all_with_confirmation() {
-  [[ $(ask_confirm "bash") == y ]] && install_bash
-  [[ $(ask_confirm "git") == y ]] && install_git
-  [[ $(ask_confirm "vim") == y ]] && install_vim
-  [[ $(ask_confirm "tmux") == y ]] && install_tmux
+dotfiles::install::all_with_confirmation() {
+  [[ $(dotfiles::install::ask_confirm "bash") == y ]] && dotfiles::install::bash
+  [[ $(dotfiles::install::ask_confirm "git") == y ]] && dotfiles::install::git
+  [[ $(dotfiles::install::ask_confirm "vim") == y ]] && dotfiles::install::vim
+  [[ $(dotfiles::install::ask_confirm "tmux") == y ]] && dotfiles::install::tmux
 }
 
-get_choices() {
+dotfiles::install::get_choices() {
   cat <<eom
 Which configuration do you want to install? (All):
 1) All
@@ -167,32 +151,32 @@ Which configuration do you want to install? (All):
 eom
 }
 
-main() {
-  [[ -z $HOME_DIR ]] && fatal "HOME directory cannot be an empty string"
-  [[ $PLATFORM != Linux && $PLATFORM != Darwin ]] && fatal "platform '$PLATFORM' is not supported"
+dotfiles::install::main() {
+  [[ -z $HOME_DIR ]] && dotfiles::log::fatal "HOME directory cannot be an empty string"
+  [[ $PLATFORM != Linux && $PLATFORM != Darwin ]] && dotfiles::log::fatal "platform '$PLATFORM' is not supported"
 
   local command=${1:-}
 
   case $command in
   install)
     local choice=
-    read -r -ep "$(get_choices) " choice
+    read -r -ep "$(dotfiles::install::get_choices) " choice
 
     [[ -z $choice ]] && choice=1
 
     case $choice in
-    1) install_all_with_confirmation ;;
-    2) install_bash ;;
-    3) install_vim ;;
-    4) install_git ;;
-    5) install_tmux ;;
-    *) fatal "Incorrect configuration number" ;;
+    1) dotfiles::install::all_with_confirmation ;;
+    2) dotfiles::install::bash ;;
+    3) dotfiles::install::vim ;;
+    4) dotfiles::install::git ;;
+    5) dotfiles::install::tmux ;;
+    *) dotfiles::log::fatal "Incorrect configuration number" ;;
     esac
     ;;
   check)
-    local cmd="$(get_install_command)"
+    local cmd="$(dotfiles::install::get_install_command)"
 
-    [[ -z $cmd ]] && fatal "cannot get install command"
+    [[ -z $cmd ]] && dotfiles::log::fatal "cannot get install command"
 
     local libraries=(
       git
@@ -200,6 +184,7 @@ main() {
       tmux
       tree
       jq
+      yq
       rsync
       curl
       source-highlight
@@ -208,19 +193,19 @@ main() {
     )
 
     for lib in ${libraries[*]}; do
-      if ! is_installed "$lib"; then
+      if ! dotfiles::install::is_command_installed "$lib"; then
         sudo sh -c "$cmd $lib"
       else
-        info "$(highlight "$lib") is already installed"
+        dotfiles::log::info "$(dotfiles::log::highlight "$lib") is already installed"
       fi
     done
 
-    warn "make also sure that bash-completion is installed"
+    dotfiles::log::warn "make also sure that bash-completion is installed"
     ;;
   *)
-    usage
+    dotfiles::install::usage
     ;;
   esac
 }
 
-main "$@"
+dotfiles::install::main "$@"
