Dotfiles installation can be made by choosing a configuration number

diff --git a/bin/install-dotfiles b/bin/install-dotfiles
--- a/bin/install-dotfiles
+++ b/bin/install-dotfiles
@@ -3,42 +3,28 @@
 set -e -u -o pipefail
 # set -x
 
-declare -r RESET_ALL="\x1b[0m"
-declare -r BG_RED="\x1b[41m"
-declare -r BG_BLUE="\x1b[44m"
-declare -r BG_MAGENTA="\x1b[45m"
-declare -r FG_WHITE="\x1b[97m"
-declare -r FG_RED="\x1b[31m"
-declare -r FG_BLUE="\x1b[34m"
-declare -r FG_MAGENTA="\x1b[35m"
-
-error() {
-    echo -e "${BG_RED}${FG_WHITE}ERROR${RESET_ALL}  ${FG_RED}$1${RESET_ALL}" >&2
+info() {
+    echo -e "\x1b[97m\xE2\x87\x92 \x1b[0m $1"
 }
 
-info() {
-    echo -e "${BG_BLUE}${FG_WHITE}INFO${RESET_ALL}  ${FG_BLUE}$1${RESET_ALL}"
+error() {
+    echo -e "\x1b[97m\x1b[41m\x21\x1b[0m \x1b[31m$1\x1b[0m" 1>&2
+    exit 1
 }
 
 warning() {
-    echo -e "${BG_MAGENTA}${FG_WHITE}WARNING${RESET_ALL}  ${FG_MAGENTA}$1${RESET_ALL}"
+    echo -e "\x1b[97m\x1b[45m\x21\x1b[0m $1"
 }
 
 declare -r HOME_DIR=${HOME:-}
 declare -r DF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
 
-if [[ -z "${HOME_DIR}" ]]; then
-    error "HOME directory cannot be an empty string"
-    exit 1
-fi
-
 create_symlink() {
-
     local target="$1"
     local symlink="$2"
     local backup="${symlink}.orig"
 
-    if [[ -f $symlink || -d $symlink ]]; then
+    if [[ ( -f $symlink && ! -L $symlink ) || -d $symlink ]]; then
         info "Moving existing location ${symlink} to ${backup}"
         mv "${symlink}" "${backup}"
     fi
@@ -53,15 +39,14 @@ create_symlink() {
 }
 
 ask_confirm() {
+    local answer=
+    local name="$1"
 
-    local confirm_config=
-    local type_config="$1"
+    read -e -p "Do you want install the ${name} configuration? [Y/n]: " answer
 
-    read -e -p "Do you want install the ${type_config} configuration? [Y/n]: " confirm_config
+    [[ -z $answer ]] && answer="y"
 
-    [[ -z $confirm_config ]] && confirm_config="y"
-
-    echo $confirm_config
+    echo $answer
 }
 
 install_bash() {
@@ -79,12 +64,15 @@ install_bash() {
     for file in ${files[*]}; do
         create_symlink "${DF_DIR}/bash/$file" "${HOME_DIR}/$file"
     done
+
+    source ~/.bashrc
 }
 
 install_git() {
     if [[ ! -f "${HOME_DIR}/git-prompt.sh" ]]; then
         info "Fetching git-prompt.sh"
-        curl -s https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh -o "${HOME_DIR}/git-prompt.sh"
+        curl -s https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh \
+            -o "${HOME_DIR}/git-prompt.sh"
     fi
 
     local files=(
@@ -103,10 +91,12 @@ install_vim() {
     create_symlink "${DF_DIR}/vim/.vimrc" "${HOME_DIR}/.vimrc"
 
     info "Fetching instant-markdown.vim "
-    curl -s https://raw.githubusercontent.com/suan/vim-instant-markdown/master/after/ftplugin/markdown/instant-markdown.vim -o "${HOME_DIR}/.vim/after/ftplugin/markdown/instant-markdown.vim"
+    curl -s https://raw.githubusercontent.com/suan/vim-instant-markdown/master/after/ftplugin/markdown/instant-markdown.vim \
+        -o "${HOME_DIR}/.vim/after/ftplugin/markdown/instant-markdown.vim"
 
     info "Fetching plug.vim"
-    curl -s https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim -o "${HOME_DIR}/.vim/autoload/plug.vim"
+    curl -s https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim \
+        -o "${HOME_DIR}/.vim/autoload/plug.vim"
 
     warning "Don't forget to run PlugInstall!"
 }
@@ -126,15 +116,50 @@ install_terminator() {
     create_symlink "${DF_DIR}/terminator/config" "${HOME_DIR}/.config/terminator/config"
 }
 
-main() {
+install_all_with_confirmation() {
     [[ $(ask_confirm "bash" ) == "y" ]] && install_bash
     [[ $(ask_confirm "git") == "y" ]] && install_git
     [[ $(ask_confirm "vim") == "y" ]] && install_vim
     [[ $(ask_confirm "tmux") == "y" ]] && install_tmux
     [[ $(ask_confirm "MySQL") == "y" ]] && install_mysql
     [[ $(ask_confirm "Terminator") == "y" ]] && install_terminator
+}
 
-    source ~/.bashrc
+get_choices() {
+    cat <<eom
+Which configuration do you want to install? (All):
+1) All
+2) Bash
+3) Vim
+4) Git
+5) Tmux
+6) Terminator
+7) MySQL
+>
+eom
+}
+
+main() {
+    if [[ -z $HOME_DIR ]]; then
+        error "HOME directory cannot be an empty string"
+        exit 1
+    fi
+
+    local choice=
+    read -p "$(get_choices) " choice
+
+    [[ -z $choice ]] && choice=1
+
+    case $choice in
+        1) install_all_with_confirmation;;
+        2) install_bash;;
+        3) install_vim;;
+        4) install_git;;
+        5) install_tmux;;
+        6) install_terminator;;
+        7) install_mysql;;
+        *) error "Wrong configuration number";;
+    esac
 }
 
 main
