add script to install base dependencies

diff --git a/install/dotfiles b/install/dotfiles
--- a/install/dotfiles
+++ b/install/dotfiles
@@ -1,23 +1,74 @@
 #!/bin/bash
+# shellcheck disable=SC2155
+# shellcheck disable=SC1090
 
 set -e -u -o pipefail
 # set -x
 
-info() {
-  echo -e "\\x1b[32m\\xE2\\x87\\x92 $1\\x1b[0m"
+declare -r SCRIPT=$(basename "$0")
+declare -r HOME_DIR=${HOME:-}
+declare -r ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
+declare -r PLATFORM=$(uname)
+
+read_help() {
+  cat <<eom
+This script helps me move into a new environment.
+
+$(highlight Usage):
+  ${SCRIPT} [command]
+
+$(highlight Commands):
+- install:    install configuration files
+- check:      list of available services
+- help:       show this help
+
+$(highlight Examples):
+  ${SCRIPT} install               (install configuration files)
+  ${SCRIPT} check                 (check dependencies)
+eom
 }
 
-error() {
+usage() {
+  echo -e "\\n$(read_help)\\n" 1>&2
+  exit 0
+}
+
+highlight() {
+  echo -e "\\x1b[33m$1\\x1b[0m"
+}
+
+info() {
+  echo -e "\\x1b[1;33m==>\\x1b[39m $1\\x1b[0m"
+}
+
+fatal() {
   echo -e "\\x1b[97m\\x1b[41m\\x21\\x1b[0m \\x1b[31m$1\\x1b[0m" 1>&2
   exit 1
 }
 
-warning() {
-  echo -e "\\x1b[97m\\x1b[45m\\x21\\x1b[0m $1"
+warn() {
+  echo -e "\\x1b[1;95m==>\\x1b[39m $1\\x1b[0m" 1>&2
 }
 
-declare -r HOME_DIR=${HOME:-}
-declare -r DF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
+is_installed() {
+  command -v "$1" >/dev/null 2>&1
+}
+
+get_install_command() {
+  local cmd=""
+
+  if is_installed apt; then
+    cmd="apt install"
+  elif is_installed pacman; then
+    cmd="pacman -S"
+  elif is_installed apt-get; then
+    cmd="apt-get install"
+  elif is_installed brew; then
+    cmd="brew install"
+  fi
+
+  echo "$cmd"
+}
 
 create_symlink() {
   local target="$1"
@@ -25,24 +76,23 @@ create_symlink() {
   local backup="${symlink}.orig"
 
   if [[ (-f $symlink && ! -L $symlink) || -d $symlink ]]; then
-    info "Moving existing location ${symlink} to ${backup}"
-    mv "${symlink}" "${backup}"
+    info "moving existing location $symlink to $backup"
+    mv "$symlink" "$backup"
   fi
 
   if [[ ! -f $target && ! -d $target ]]; then
-    error "Target ${target} is neither a file nor a directory"
-    exit 1
+    fatal "target $target is neither a file nor a directory"
   fi
 
-  info "Creating symlink ${symlink}"
-  ln -svf "${target}" "${symlink}"
+  info "creating symlink $symlink"
+  ln -svf "$target" "$symlink"
 }
 
 ask_confirm() {
   local answer=
   local name="$1"
 
-  read -epr "$(echo -e "Do you want to install \\x1b[33m${name}\\x1b[0m configuration? [Y/n]:") " answer
+  read -epr "$(echo -e "Do you want to install $(highlight "$name") configuration? [Y/n]:") " answer
 
   [[ -z $answer ]] && answer="y"
 
@@ -64,17 +114,17 @@ install_bash() {
   )
 
   for file in ${files[*]}; do
-    create_symlink "${DF_DIR}/bash/$file" "${HOME_DIR}/$file"
+    create_symlink "$ROOT_DIR/bash/$file" "$HOME_DIR/$file"
   done
 
   source ~/.bashrc
 }
 
 install_git() {
-  if [[ ! -f "${HOME_DIR}/git-prompt.sh" ]]; then
+  if [[ ! -f "$HOME_DIR/git-prompt.sh" ]]; then
     info "Fetching git-prompt.sh"
     curl -s https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh \
-      -o "${HOME_DIR}/git-prompt.sh"
+      -o "$HOME_DIR/git-prompt.sh"
   fi
 
   local files=(
@@ -85,34 +135,34 @@ install_git() {
   )
 
   for file in ${files[*]}; do
-    create_symlink "${DF_DIR}/git/$file" "${HOME_DIR}/$file"
+    create_symlink "$ROOT_DIR/git/$file" "$HOME_DIR/$file"
   done
 }
 
 install_vim() {
-  create_symlink "${DF_DIR}/vim/.vim" "${HOME_DIR}/.vim"
-  create_symlink "${DF_DIR}/vim/.vimrc" "${HOME_DIR}/.vimrc"
+  create_symlink "$ROOT_DIR/vim/.vim" "$HOME_DIR/.vim"
+  create_symlink "$ROOT_DIR/vim/.vimrc" "$HOME_DIR/.vimrc"
 
   info "Fetching instant-markdown.vim "
   curl -s https://raw.githubusercontent.com/instant-markdown/vim-instant-markdown/master/ftplugin/markdown/instant-markdown.vim \
-    -o "${HOME_DIR}/.vim/after/ftplugin/markdown/instant-markdown.vim"
+    -o "$HOME_DIR/.vim/after/ftplugin/markdown/instant-markdown.vim"
 
   info "Fetching plug.vim"
   curl -s https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim \
-    -o "${HOME_DIR}/.vim/autoload/plug.vim"
+    -o "$HOME_DIR/.vim/autoload/plug.vim"
 
   warning "Don't forget to run PlugInstall!"
 }
 
 install_tmux() {
-  create_symlink "${DF_DIR}/tmux/.tmux.conf" "${HOME_DIR}/.tmux.conf"
+  create_symlink "$ROOT_DIR/tmux/.tmux.conf" "$HOME_DIR/.tmux.conf"
 }
 
 install_all_with_confirmation() {
-  [[ $(ask_confirm "bash") == "y" ]] && install_bash
-  [[ $(ask_confirm "git") == "y" ]] && install_git
-  [[ $(ask_confirm "vim") == "y" ]] && install_vim
-  [[ $(ask_confirm "tmux") == "y" ]] && install_tmux
+  [[ $(ask_confirm "bash") == y ]] && install_bash
+  [[ $(ask_confirm "git") == y ]] && install_git
+  [[ $(ask_confirm "vim") == y ]] && install_vim
+  [[ $(ask_confirm "tmux") == y ]] && install_tmux
 }
 
 get_choices() {
@@ -128,24 +178,59 @@ eom
 }
 
 main() {
-  if [[ -z $HOME_DIR ]]; then
-    error "HOME directory cannot be an empty string"
-    exit 1
-  fi
+  [[ -z $HOME_DIR ]] && fatal "HOME directory cannot be an empty string"
+  [[ $PLATFORM != Linux && $PLATFORM != Darwin ]] && fatal "platform '$PLATFORM' is not supported"
 
-  local choice=
-  read -r -ep "$(get_choices) " choice
+  local command=${1:-}
 
-  [[ -z $choice ]] && choice=1
+  case $command in
+  install)
+    local choice=
+    read -r -ep "$(get_choices) " choice
 
-  case $choice in
-  1) install_all_with_confirmation ;;
-  2) install_bash ;;
-  3) install_vim ;;
-  4) install_git ;;
-  5) install_tmux ;;
-  *) error "Wrong configuration number" ;;
+    [[ -z $choice ]] && choice=1
+
+    case $choice in
+    1) install_all_with_confirmation ;;
+    2) install_bash ;;
+    3) install_vim ;;
+    4) install_git ;;
+    5) install_tmux ;;
+    *) fatal "Incorrect configuration number" ;;
+    esac
+    ;;
+  check)
+    local cmd="$(get_install_command)"
+
+    [[ -z $cmd ]] && fatal "cannot get install command"
+
+    local libraries=(
+      git
+      vim
+      tmux
+      tree
+      jq
+      rsync
+      curl
+      source-highlight
+      bat
+      fzf
+    )
+
+    for lib in ${libraries[*]}; do
+      if ! is_installed "$lib"; then
+        sudo sh -c "$cmd $lib"
+      else
+        info "$(highlight "$lib") is already installed"
+      fi
+    done
+
+    warn "make also sure that bash-completion is installed"
+    ;;
+  *)
+    usage
+    ;;
   esac
 }
 
-main
+main "$@"
