reformat scripts

diff --git a/install/php-deps b/install/php-deps
--- a/install/php-deps
+++ b/install/php-deps
@@ -4,30 +4,30 @@ set -e -u -o pipefail
 # set -x
 
 info() {
-    echo -e "\\x1b[32m\\xE2\\x87\\x92 $1\\x1b[0m"
+  echo -e "\\x1b[32m\\xE2\\x87\\x92 $1\\x1b[0m"
 }
 
 error() {
-    echo -e "\\x1b[97m\\x1b[41m\\x21\\x1b[0m \\x1b[31m$1\\x1b[0m" 1>&2
-    exit 1
+  echo -e "\\x1b[97m\\x1b[41m\\x21\\x1b[0m \\x1b[31m$1\\x1b[0m" 1>&2
+  exit 1
 }
 
 main() {
-    declare -a packages=(
-        squizlabs/php_codesniffer
-        phpmd/phpmd
-        phpspec/phpspec
-        phpunit/phpunit
-    )
+  declare -a packages=(
+    squizlabs/php_codesniffer
+    phpmd/phpmd
+    phpspec/phpspec
+    phpunit/phpunit
+  )
 
-    command -v composer >/dev/null 2>&1 || \
-        error "composer is required but it is not installed. \\xE2\\x98\\xB9"
+  command -v composer >/dev/null 2>&1 ||
+    error "composer is required but it is not installed. \\xE2\\x98\\xB9"
 
-    info "Installing global PHP dependencies..."
+  info "Installing global PHP dependencies..."
 
-    composer global require "${packages[@]}"
+  composer global require "${packages[@]}"
 
-    info "Composer bin directory $(composer --global config data-dir)/vendor/bin/ will be added to PATH, see ~/.bash_export"
+  info "Composer bin directory $(composer --global config data-dir)/vendor/bin/ will be added to PATH, see ~/.bash_export"
 }
 
 main
