Fix a few code style related issues

diff --git a/install/php-deps b/install/php-deps
--- a/install/php-deps
+++ b/install/php-deps
@@ -4,11 +4,11 @@ set -e -u -o pipefail
 # set -x
 
 info() {
-    echo -e "\x1b[32m\xE2\x87\x92 $1\x1b[0m"
+    echo -e "\\x1b[32m\\xE2\\x87\\x92 $1\\x1b[0m"
 }
 
 error() {
-    echo -e "\x1b[97m\x1b[41m\x21\x1b[0m \x1b[31m$1\x1b[0m" 1>&2
+    echo -e "\\x1b[97m\\x1b[41m\\x21\\x1b[0m \\x1b[31m$1\\x1b[0m" 1>&2
     exit 1
 }
 
@@ -21,7 +21,7 @@ main() {
     )
 
     command -v composer >/dev/null 2>&1 || \
-        error "composer is required but it is not installed. \xE2\x98\xB9"
+        error "composer is required but it is not installed. \\xE2\\x98\\xB9"
 
     info "Installing global PHP dependencies..."
 
